/** Jenkins 2.0 Buildfile
 *
 * Master Jenkins 2.0 can be started by typing:
 * docker run -d -p 8090:8080 --name jenkins blacklabelops/jenkins
 *
 * Slave 'docker' can be started by typing:
 * docker run -d -v /var/run/docker.sock:/var/run/docker.sock --link jenkins:jenkins -e "SWARM_CLIENT_LABELS=docker" blacklabelops/swarm-dockerhost
 **/

node('docker') {
    checkout scm
    job = load 'buildscripts/buildImage.groovy'
    settings = load 'buildscripts/settings.groovy'
    javaargs = ["jdk",
     settings.openjdk_8_java_major_version,
     settings.openjdk_8_java_update_version,
     settings.openjdk_8_java_build_number] as String[]
    dockerTags = ["latest"] as String[]
    dockerImages = ["blacklabelops/alpine:3.3"] as String[]
    job.buildJobPullImages(dockerImages)
    job.buildJobCI("java-openjdk",settings.dockerImageName,dockerTags,settings.dockerTestCommandsJDK,job.getBranchName(),javaargs)
}
