#!/bin/bash

#------------------
# CONTAINER VARIABLES
#------------------
export ORACLE_6_JAVA_MAJOR_VERSION=6
export ORACLE_6_JAVA_UPDATE_VERSION=45
export ORACLE_6_JAVA_BUILD_NUMBER=06

export ORACLE_7_JAVA_MAJOR_VERSION=7
export ORACLE_7_JAVA_UPDATE_VERSION=80
export ORACLE_7_JAVA_BUILD_NUMBER=15

export ORACLE_8_JAVA_MAJOR_VERSION=8
export ORACLE_8_JAVA_UPDATE_VERSION=74
export ORACLE_8_JAVA_BUILD_NUMBER=02

export OPENJDK_8_JAVA_MAJOR_VERSION=8
export OPENJDK_8_JAVA_UPDATE_VERSION=66
export OPENJDK_8_JAVA_BUILD_NUMBER=17-r2

export OPENJDK_7_JAVA_MAJOR_VERSION=7
export OPENJDK_7_JAVA_UPDATE_VERSION=90
export OPENJDK_7_JAVA_BUILD_NUMBER=2.6.3-r1
